apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  SECRET_KEY: "supersecretkey123skljflsilkjalsjfosdqweisjnvsljsklfds"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  GEMINI_API_KEY: "AIzaSyD6DE4f4u_xAbwnwcIi2pwbUX3H4wDOJW0"